---
db_pass: e79c9761d0b54698a83ff3f93769e309
admin_pass: 46041386be534591ad24902bf72071B
secret_key: b495a05c396843b6b47ac944a72c92ed
nevercache_key: b5d87bb4e17c483093296fa321056bdc
# You need to create a Twitter application at https://dev.twitter.com
# in order to get the credentials required for Mezzanine's
# twitter integration.
#
# See http://mezzanine.jupo.org/docs/twitter-integration.html
# for details on Twitter integration
twitter_access_token_key: 1904452855727104001-FkQFJuGhyN5Rnq5cAJsnRz1CqfW2yA
twitter_access_token_secret: WKQi3BoNYLWcj1bwXpr1MHx9w4J3KebOdDpaiI3lxoFks
twitter_consumer_key: X5ROdp7npLH8NRjsDrqP8KT6c
twitter_consumer_secret: JpahrUnpBz1ASAHvH8gzaAJuewlQBownYO5QbtYAGamZ3nHAJ4
...
